/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package semana2;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author epimentel
 */
public class TareaAcademica extends javax.swing.JFrame {

    /**
     * Creates new form TareaAcademica
     */
    
    int[] numbers;
    
    public TareaAcademica() {
        initComponents();
    }
    
    public void listNumbers() {
        for (int i=0; i< numbers.length; i++) {
            jTextArea1.append("[" + Integer.toString(numbers[i]) + "]");
        }
    }
    
    public void quick(int primero, int ultimo){
        int i,j,pivote,auxiliar;
        i=primero;
        j=ultimo; 
        pivote=numbers[(primero + ultimo)/2];
        do {
            while(numbers[i]<pivote){
                i++;
            }
            while(numbers[j]>pivote){
                j--;
            }
            // aqui hacemos el intercambio
            if (i<=j){
                auxiliar=numbers[i];
                numbers[i]=numbers[j];
                numbers[j]=auxiliar;
                i++;
                j--;
            }
        }while(i<=j);
        // Realizando la recursividad
        if (i<j){
            quick(primero,i);
        }
        if(i<j){
            quick(i,ultimo);
        }

        jTextArea1.append("\n\nMetodo QuickSort\n");
        jTextArea1.append("------------------------\n");
        listNumbers();
    }
    
    public void insercion(int[] arreglo, int n){       
        int i,j,auxiliar;
        for(i=1;i<n;i++){
            auxiliar=arreglo[i];
            j=i-1;
            while(j>=0 && arreglo[j]>auxiliar){
                arreglo[j+1]=arreglo[j];
                j=j-1;
            }
            arreglo[j+1]=auxiliar;
        }
        jTextArea1.append("\n\nInsercion\n");
        jTextArea1.append("------------------------\n");
        
        for (int b=0; b < arreglo.length; b++) {
            jTextArea1.append("[" + Integer.toString(arreglo[b]) + "]");
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnShell = new javax.swing.JButton();
        btnBurbuja = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        btnQuickSort = new javax.swing.JButton();
        btnInsertion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        btnShell.setText("Shell");
        btnShell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShellActionPerformed(evt);
            }
        });

        btnBurbuja.setText("Burbuja");
        btnBurbuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurbujaActionPerformed(evt);
            }
        });

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnQuickSort.setText("QuickSort");
        btnQuickSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickSortActionPerformed(evt);
            }
        });

        btnInsertion.setText("Insercion");
        btnInsertion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBurbuja)
                        .addGap(18, 18, 18)
                        .addComponent(btnShell)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuickSort)
                        .addGap(18, 18, 18)
                        .addComponent(btnInsertion)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShell)
                    .addComponent(btnLoad)
                    .addComponent(btnBurbuja)
                    .addComponent(btnQuickSort)
                    .addComponent(btnInsertion))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShellActionPerformed
        if (numbers != null) {
            int salto,i,j,k,auxiliar;
            salto = numbers.length/2;
            while(salto>0){
                for(i=salto;i<numbers.length; i++){
                    j=i-salto;
                    while(j>=0){
                        k=j+salto;
                        if (numbers[j]<=numbers[k]){
                            j=-1;
                        }else{
                            auxiliar=numbers[j];
                            numbers[j]=numbers[k];
                            numbers[k]=auxiliar;
                            j=j-salto;
                        }
                    }
                }
                salto=salto/2;
            }

            jTextArea1.append("\n\nMetodo Shell\n");
            jTextArea1.append("------------------------\n");
            listNumbers();
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Lista vacia, seleccionar boton load", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnShellActionPerformed

    private void btnBurbujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurbujaActionPerformed
        if (numbers != null){
            for (int i=0; i < numbers.length; i++) {
                for (int j=0; j < numbers.length - 1; j++) {
                    if (numbers[j] > numbers[j + 1]) {
                        Integer temp = numbers[j];
                        numbers[j] = numbers[j + 1];
                        numbers[j + 1] = temp;
                    }
                }
            }
            jTextArea1.append("\n\nMetodo Burbuja\n");
            jTextArea1.append("------------------------\n");
            listNumbers();
        }else{
            JOptionPane.showMessageDialog(new JFrame(), "Lista vacia, seleccionar boton load", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btnBurbujaActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        int setNumber = 7;
        jTextArea1.setText("");
        jTextArea1.setText("Vector Base\n");
        jTextArea1.append("------------------------\n");
        numbers = new int[setNumber];
        
        for (int i=0; i< numbers.length; i++) {
            numbers[i] = (int)(Math.random()*10);
        }
        
        listNumbers();
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnQuickSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickSortActionPerformed
        if ( numbers != null ) {
           quick(0, numbers.length - 1); 
        } else {
         JOptionPane.showMessageDialog(new JFrame(), "Lista vacia, seleccionar boton load", "Error", JOptionPane.ERROR_MESSAGE);   
        }
    }//GEN-LAST:event_btnQuickSortActionPerformed

    private void btnInsertionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertionActionPerformed
        // TODO add your handling code here:
        int vector[]=new int[5];
        for (int i=0; i<5; i++){
            vector[i]= Integer.parseInt(JOptionPane.showInputDialog("Ingrese elemento del indice: " + i));
            insercion(vector, i + 1);
            
        }
    }//GEN-LAST:event_btnInsertionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TareaAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TareaAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TareaAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TareaAcademica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TareaAcademica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBurbuja;
    private javax.swing.JButton btnInsertion;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnQuickSort;
    private javax.swing.JButton btnShell;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
